CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SEXO ENUM('M', 'F'),
	TELEFONE VARCHAR(11),
	EMAIL VARCHAR(100) UNIQUE
);


CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) NOT NULL,
	PLACA VARCHAR(7) NOT NULL,
	ID_FK_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_FK_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);
	

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	NOMECOR VARCHAR(30) NOT NULL,
	ID_FK_CLIENTE INT,
	FOREIGN KEY(ID_FK_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

INSERT INTO CLIENTE VALUES (NULL, 'JOAO', 'M', '8199999999', 'JOAO@HOTMAIL.COM');
INSERT INTO CLIENTE VALUES (NULL, 'MARIA', 'F', '8188888888', 'MARIA@GMAIL.COM');
INSERT INTO CLIENTE VALUES (NULL, 'PEDRO', 'M', '8177777777', 'PEDRO@YAHOO.COM');
INSERT INTO CLIENTE VALUES (NULL, 'CARLA', 'M', '8166666666', 'CARLA@BOL.COM');

INSERT INTO CARRO VALUES (NULL, 'FIAT', 'PEQ2962', 1);
INSERT INTO CARRO VALUES (NULL, 'FORD', 'PUQ1932', 4);
INSERT INTO CARRO VALUES (NULL, 'FIAT', 'MLO3455', 3);
INSERT INTO CARRO VALUES (NULL, 'FIAT', 'PJK1100', 2);

INSERT INTO COR VALUES (NULL, 'PRATA', 1);
INSERT INTO COR VALUES (NULL, 'PRETO', 1);
INSERT INTO COR VALUES (NULL, 'BRANCO', 2);
INSERT INTO COR VALUES (NULL, 'CINZA', 2);
INSERT INTO COR VALUES (NULL, 'VERMELHO', 4);
INSERT INTO COR VALUES (NULL, 'AMARELO', 3);


SELECT CL.NOME, CA.MARCA, CA.PLACA, CO.NOMECOR
FROM CLIENTE CL
INNER JOIN CARRO CA
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
INNER JOIN COR CO
ON CL.IDCLIENTE = CO.ID_FK_CLIENTE;

SELECT NOME, PLACA, NOMECOR, COUNT(*)
FROM CLIENTE CL
INNER JOIN CARRO CA
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
INNER JOIN COR CO
ON CL.IDCLIENTE = CO.ID_FK_CLIENTE
GROUP BY NOME;

SELECT NOME, PLACA
FROM CLIENTE CL
INNER JOIN CARRO CA 
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
WHERE SEXO = 'M';

SELECT NOME AS 'CLIENTE', PLACA, NOMECOR AS COR, COUNT(*)
FROM CLIENTE CL
INNER JOIN CARRO CA 
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
INNER JOIN COR CO
ON CL.IDCLIENTE = CO.ID_FK_CLIENTE
WHERE NOMECOR = 'VERDE'
GROUP BY NOME;

SELECT CL.NOME, CA.MARCA, COUNT(*)
FROM CLIENTE CL
INNER JOIN CARRO CA
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
GROUP BY MARCA;

CREATE VIEW RELATORIO AS
SELECT  CL.NOME AS CLIENTE, 
		CL.EMAIL, 
		CA.MARCA
FROM CLIENTE CL
INNER JOIN CARRO CA
ON CL.IDCLIENTE = CA.ID_FK_CLIENTE
WHERE MARCA = 'FIAT';

+---------+------------------+-------+
| CLIENTE | EMAIL            | MARCA |
+---------+------------------+-------+
| JOAO    | JOAO@HOTMAIL.COM | FIAT  |
| PEDRO   | PEDRO@YAHOO.COM  | FIAT  |
| MARIA   | MARIA@GMAIL.COM  | FIAT  |
+---------+------------------+-------+
/* PROCEDURES SIMPLES */
CREATE PROCEDURE NOME()
BEGIN
	ACAO;
END
$

SELECT 10 + 10$

CREATE PROCEDURE CONTA()
BEGIN
	SELECT 10 + 10 AS "SOMA";
END
$

/* PROCEDURES COM PARAMENTROS*/

CREATE PROCEDURE CONTA1(N1 INT, N2 INT)
BEGIN
	SELECT N1 + N2 AS "SOMA";
END
$

/* PROCEDURES COM TABELAS */

CREATE TABLE CURSO(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSO VALUES(NULL, 'BANCO DE DADOS FUNDAMENTOS', 25, 200.00);

SELECT * FROM CURSO;

DELIMITER #

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30), P_HORAS INT(3), P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSO VALUES(NULL, P_NOME, P_HORAS, P_PRECO);	
END
#

CALL CAD_CURSO('BI SQL SERVER', 30, 300.00);

DELIMITER #

CREATE PROCEDURE SEL_CURSO()
BEGIN
	SELECT IDCURSO, NOME, HORAS, VALOR FROM CURSO;
END
#
/* FUNCOES DE AGREGACAO */

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDOR VALUES(NULL, 'CARLOS','M', 903945.98, 724682.34, 345085.90);
INSERT INTO VENDEDOR VALUES(NULL, 'MARIA','F', 9458.98, 43546.34, 54657587.90);
INSERT INTO VENDEDOR VALUES(NULL, 'ANA','F',2455.98, 45435.34, 345085.90);
INSERT INTO VENDEDOR VALUES(NULL, 'PAULO','M', 35457.98, 343243563.34, 345085.90);
INSERT INTO VENDEDOR VALUES(NULL, 'CRISTINA','F', 093034.98, 453454.34, 345085.90);
INSERT INTO VENDEDOR VALUES(NULL, 'JOAO', 'M',445546546.98, 724682.34, 345085.90);
INSERT INTO VENDEDOR VALUES(NULL, 'JULIA','F', 3443.98, 43234234.34, 435457.90);
INSERT INTO VENDEDOR VALUES(NULL, 'PEDRO', 'M', 234235.98, 724682.34, 345085.90);

SELECT MAX(FEVEREIRO) AS MAIOR_FEV FROM VENDEDOR;
SELECT MIN(FEVEREIRO) AS MENOR_FEV FROM VENDEDOR;
SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDOR;

SELECT 	MAX(FEVEREIRO) AS MAIOR_FEV,
		MIN(FEVEREIRO) AS MENOR_FEV,
		TRUNCATE(AVG(FEVEREIRO),2) AS MEDIA_FEV 
FROM VENDEDOR;

SELECT  SUM(JANEIRO) AS TOTAL_JAN,
		SUM(FEVEREIRO) AS TOTAL_FEV,
		SUM(MARCO) AS TOTAL_MAR 
FROM VENDEDOR;

SELECT  SEXO, 
		SUM(JANEIRO) AS TOTAL_JAN,
		SUM(FEVEREIRO) AS TOTAL_FEV,
		SUM(MARCO) AS TOTAL_MAR 
FROM VENDEDOR
GROUP BY SEXO
ORDER BY SEXO DESC;

SELECT  NOME, 
		MARCO AS TOTAL_MAR 
FROM VENDEDOR
ORDER BY TOTAL_MAR ASC;

/* SUBQUERY */
SELECT NOME, FEVEREIRO FROM VENDEDOR
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDOR);


SELECT NOME,
		JANEIRO,
		FEVEREIRO,
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3, 2) AS "MEDIA"
		FROM VENDEDOR;
		
	