CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SEXO ENUM('M', 'F'),
	TELEFONE VARCHAR(11),
	EMAIL VARCHAR(100) UNIQUE
);


CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE NOT NULL,
	PLACA VARCHAR(7) UNIQUE NOT NULL,
	ID_CLIENTE INT UNIQUE, 
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	NOMECOR VARCHAR(30) NOT NULL,
	ID_CLIENTE INT, 
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);
