INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'CENTRO', 'BELO HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA B', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA C', 'CENTRO', 'SÃO PAULO', 'SP', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA D', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA E', 'RECIFE', 'PERNAMBUCO', 'PE', 5);
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'BARBACENA', 'BELO HORIZONTE', 'MG', 7);
INSERT INTO ENDERECO VALUES (NULL, 'RUA E', 'PAULISTA', 'PERNAMBUCO', 'PE', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA A', 'BARBACENA', 'BELO HORIZONTE', 'MG', 8);
INSERT INTO ENDERECO VALUES (NULL, 'RUA X', 'BARBACENA', 'BELO HORIZONTE', 'MG', 8);

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90987879', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90987879', 2);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90987879', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90123439', 3);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '90987122', 6);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90993849', 7);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90987879', 7);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '90987879', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '90987879', 6);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '90987879', 2);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '90987879', 1);

SELECT NOME, SEXO, BAIRRO, NOW() AS DATA
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE
WHERE BAIRRO = 'CENTRO';

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, 
ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO ON 	CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;
 